add footer-mobile
VolodymyrPyts/tren_project pull request #13
Opened 2022-04-02 10:39 UTC by IvanChudiyovuch

Зробив розмітку секції, написав деякі стилі

2022-04-02 17:28 UTC, VolodymyrPyts requested changes

2022-04-02 17:28 UTC, VolodymyrPyts commented on src/sass/_footer.scss
> +
усі сброси зробили в окремому файлі тому видали з відси

2022-04-02 17:28 UTC, VolodymyrPyts commented on src/sass/_footer.scss
> +    background: #FFF5F6;
є файл з рут змінним для кольорів перероби з використанням їх

2022-04-02 17:28 UTC, VolodymyrPyts commented on src/partials/footer.html
> +            <a href="tel:+610383766284" class="tel-item"> <span class="tel-item--black">Feel free to contact</span> +61 (0) 383 766 284</a>
я міркую тут "а" треба ставити лише на номер, що до тексту то це просто параграф він не має бути посиланням

2022-04-02 19:02 UTC, IvanChudiyovuch commented on src/sass/_footer.scss
> +
Виправив

2022-04-02 19:02 UTC, IvanChudiyovuch commented on src/sass/_footer.scss
> +    background: #FFF5F6;
виправив

2022-04-02 19:03 UTC, IvanChudiyovuch commented on src/partials/footer.html
> +            <a href="tel:+610383766284" class="tel-item"> <span class="tel-item--black">Feel free to contact</span> +61 (0) 383 766 284</a>
Зробив як ти сказав

2022-04-03 07:04 UTC, VolodymyrPyts approved these changes

2022-04-03 07:05 UTC, VolodymyrPyts approved these changes

2022-04-03 09:08 UTC, VolodymyrPyts commented
+

2022-04-04 08:27 UTC, closed without merging